config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  
 


  root to: 'products#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_shipping_PayGuest', defaults: { format: 'json' }
      get 'get_shipping_PayFormer', defaults: { format: 'json' }
      get :buy_confirm
      post :purchase
      get :done
    end
  end

  get '/signup', to: "signup#index"

  resource :mypage, only: [:show] do
    collection do
      get :identification
      get :profile
      get :card
      get :logout
    end
  end


  #以下作業用およびテスト用。

  resources :tests, only: [:index, :new, :create]
  get '/tmp', to: 'tmps#index'


  resources :registers, only: [:index] do
    collection do
      get :first
      get :second
      get :third
      get :forth
      get :fifth
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :zipcode, :prefecture, :city, :district, :building, presence: true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :products
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :products
end

app/models/fromprefecture.rb
class Fromprefecture < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :description, :term_id, :size_id, :condition_id, :shipping_id, :delivery_id, :fromprefecture_id, :category_id, :user_id,  presence: true
  has_many_attached :images, dependent: :destroy

  validate :image_presence

  def image_presence
    images.attached?
  end

  belongs_to :user, optional: true
  belongs_to :brand, optional: true
  belongs_to :term, optional: true
  belongs_to :size, optional: true
  belongs_to :condition, optional: true
  belongs_to :shipping, optional: true
  belongs_to :delivery, optional: true
  belongs_to :fromprefecture, optional: true
  belongs_to :category, optional: true
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :products
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
  validates :uid,presence: true
  validates :provider,presence: true
  validates :user_id,presence: true
end

app/models/term.rb
class Term < ApplicationRecord
  has_many :products
end

app/models/test.rb
class Test < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  validates :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, presence: true
  has_one :address
  has_many :products
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  def index
  end

  def first
  end

  def second
  end

  def third
  end

  def forth
  end

  def fifth
  end
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/tmps_helper.rb
module TmpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/registers/_index_five.html.haml
%header.single-header-five
  .header-min
    %h1
      %link_to{href: ""}
        = image_tag "/fmarket_logo_red.svg", height:'50', width:'185'
    %nav
      %ol.clearfix
        %li.procedure_one
          会員情報
          %br/
          .progress-status
        %li.procedure_two
          電話番号認証
          %br/
          .progress-status
        %li.procedure_three
          お届け先住所
          %br/
          .progress-status
        %li.procedure_four
          支払い方法
          %br/
          .progress-status
        %li.procedure_five
          完了
          %br/
          .progress-status
%main.page-five
  %h2 会員登録完了
  %form
    -# %input{name: "", type: "hidden", value: ""}/
    .contents
      %p ありがとうございます。
      %p 会員登録が完了しました。
      = link_to root_path , class: 'button-next' do
        %p メルカリをはじめる
  %link_to.banner
    %img{src: "//www-mercari-jp.akamaized.net/assets/img/signup/jp/banner-pc.jpg?2091621301", width: "100%"}
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        %link_to{href: ""} プライバシーポリシー
      %li
        %link_to{href: ""} メルカリ利用規約
      %li
        %link_to{href: ""} 特定商取引に関する表記
  %link_to{href: "https://www.mercari.com/jp/"}
    = image_tag "/logo_gray.svg", height:'65', width:'80'
  %p
    %small © Mercari, Inc.

app/views/registers/_index_four.html.haml
%header.single-header-four
  .header-min
    %h1
      %link_to{href: ""}
        = image_tag "/fmarket_logo_red.svg", height:'50', width:'185'
    %nav
      %ol.clearfix
        %li.procedure_one
          会員情報
          %br/
          .progress-status
        %li.procedure_two
          電話番号認証
          %br/
          .progress-status
        %li.procedure_three
          お届け先住所
          %br/
          .progress-status
        %li.procedure_four
          支払い方法
          %br/
          .progress-status
        %li.procedure_five
          完了
          %br/
          .progress-status
%main.page-four
  %h2 お支払い方法
  %form
    -# %input{name: "", type: "hidden", value: ""}/
    .contents
      .form-content
        %label{for: "payment-card"} カード番号
        %span 必須
        %input{name: "payment-card", placeholder: "半角数字のみ", type: "text", value: ""}/
        %ul
          %li
            %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2091621301", width: "49", height: "20"}/
          %li
            %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2091621301", width: "49", height: "20"}/
          %li
            %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2091621301", width: "49", height: "20"}/
          %li
            %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2091621301", width: "49", height: "20"}/
          %li
            %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2091621301", width: "49", height: "20"}/
          %li
            %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2091621301", width: "49", height: "20"}/
          %li
            %img{src: "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2091621301", width: "49", height: "20"}/
      .form-content
        %label{for: "payment-card-expire"} 有効期限
        %span 必須
        .credit-card
          %select{name: "payment-card-expire-mm"}
            %option{value: ""} --
            %option{value: "01"} 01
            %option{value: "02"} 02
            %option{value: "03"} 03
            %option{value: "04"} 04
            %option{value: "05"} 05
            %option{value: "06"} 06
            %option{value: "07"} 07
            %option{value: "08"} 08
            %option{value: "09"} 09
            %option{value: "10"} 10
            %option{value: "11"} 11
            %option{value: "12"} 12
          %span 月
          %select{name: "payment-card-expire-yy"}
            %option{value: ""} --
            %option{value: "20"} 20
            %option{value: "21"} 21
            %option{value: "22"} 22
            %option{value: "23"} 23
            %option{value: "24"} 24
            %option{value: "25"} 25
            %option{value: "26"} 26
            %option{value: "27"} 27
            %option{value: "28"} 28
            %option{value: "29"} 29
            %option{value: "30"} 30
          %span 年
      .form-content
        %label{for: "security-code"} セキュリティコード
        %span 必須
        %input{name: "security-code", placeholder: "カード背面4桁もしくは3桁の番号", type: "text", value: ""}/
        %link_to{href: "", target: "_blank"}
          %i.fas.fa-question-circle
          カード裏面の番号とは？
      = link_to fifth_registers_path , class: 'button-next' do
        %p 次へ進む
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        %link_to{href: ""} プライバシーポリシー
      %li
        %link_to{href: ""} メルカリ利用規約
      %li
        %link_to{href: ""} 特定商取引に関する表記
  %link_to{href: "https://www.mercari.com/jp/"}
    = image_tag "/logo_gray.svg", height:'65', width:'80'
  %p
    %small © Mercari, Inc.

app/views/registers/_index_one.html.haml
%header.single-header-one
  .header-min
    %h1
      %link_to{href: ""}
        = image_tag "/fmarket_logo_red.svg", height:'50', width:'185'
    %nav
      %ol.clearfix
        %li.procedure_one
          会員情報
          %br/
          .progress-status
        %li.procedure_two
          電話番号認証
          %br/
          .progress-status
        %li.procedure_three
          お届け先住所
          %br/
          .progress-status
        %li.procedure_four
          支払い方法
          %br/
          .progress-status
        %li.procedure_five
          完了
          %br/
          .progress-status
%main.page-one
  %h2 会員情報入力
  %form
    -# %input{name: "", type: "hidden", value: ""}/
    %div
      .form-group
        %label{for: "nickname"} ニックネーム
        %span 必須
        %input{name: "nickname", placeholder: "例) メルカリ太郎", type: "text", value: ""}/
      .form-group
        %label{for: "email"} メールアドレス
        %span 必須
        %input{name: "email", placeholder: "PC・携帯どちらでも可", type: "email", value: ""}/
      .form-group
        %label{for: "password"} パスワード
        %span 必須
        %input{name: "password", placeholder: "7文字以上の半角英数字", type: "password"}/
        %p
          ※ 英字と数字の両方を含めて設定してください
        .password-revelation
          %div
            %input#reveal-password{type: "checkbox"}/
            %label{for: "reveal_password"} パスワードを表示する
      .form-group
        %h3.text-left.l-chapter-sub-head 本人確認
        %p.l-single-text
          安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
      .form-group
        %label お名前(全角)
        %span.form-require 必須
        .form-require-half
          %input#half{name: "family_name_kanji", placeholder: "例) 山田", type: "text", value: ""}/
          %input#half{name: "first_name_kanji", placeholder: "例) 彩", type: "text", value: ""}/
      .form-group
        %label お名前カナ(全角)
        %span.form-require 必須
        .form-require-half
          %input#half{name: "family_name_kanji", placeholder: "例) ヤマダ", type: "text", value: ""}/
          %input#half{name: "first_name_kanji", placeholder: "例) アヤ", type: "text", value: ""}/
      .form-group
        %label{for: "birthday"} 生年月日
        %span 必須
        %br/
        .birthday-select-wrap
          %select{name: "year"}
            %option{value: ""} --
            %option{value: "2020"} 2020
            %option{value: "2019"} 2019
            %option{value: "2018"} 2018
            %option{value: "2017"} 2017
            %option{value: "2016"} 2016
            %option{value: "2015"} 2015
            %option{value: "2014"} 2014
            %option{value: "2013"} 2013
            %option{value: "2012"} 2012
            %option{value: "2011"} 2011
            %option{value: "2010"} 2010
            %option{value: "2009"} 2009
            %option{value: "2008"} 2008
            %option{value: "2007"} 2007
            %option{value: "2006"} 2006
            %option{value: "2005"} 2005
            %option{value: "2004"} 2004
            %option{value: "2003"} 2003
            %option{value: "2002"} 2002
            %option{value: "2001"} 2001
            %option{value: "2000"} 2000
            %option{value: "1999"} 1999
            %option{value: "1998"} 1998
            %option{value: "1997"} 1997
            %option{value: "1996"} 1996
            %option{value: "1995"} 1995
            %option{value: "1994"} 1994
            %option{value: "1993"} 1993
            %option{value: "1992"} 1992
            %option{value: "1991"} 1991
            %option{value: "1990"} 1990
            %option{value: "1989"} 1989
            %option{value: "1988"} 1988
            %option{value: "1987"} 1987
            %option{value: "1986"} 1986
            %option{value: "1985"} 1985
            %option{value: "1984"} 1984
            %option{value: "1983"} 1983
            %option{value: "1982"} 1982
            %option{value: "1981"} 1981
            %option{value: "1980"} 1980
            %option{value: "1979"} 1979
            %option{value: "1978"} 1978
            %option{value: "1977"} 1977
            %option{value: "1976"} 1976
            %option{value: "1975"} 1975
            %option{value: "1974"} 1974
            %option{value: "1973"} 1973
            %option{value: "1972"} 1972
            %option{value: "1971"} 1971
            %option{value: "1970"} 1970
            %option{value: "1969"} 1969
            %option{value: "1968"} 1968
            %option{value: "1967"} 1967
            %option{value: "1966"} 1966
            %option{value: "1965"} 1965
            %option{value: "1964"} 1964
            %option{value: "1963"} 1963
            %option{value: "1962"} 1962
            %option{value: "1961"} 1961
            %option{value: "1960"} 1960
            %option{value: "1959"} 1959
            %option{value: "1958"} 1958
            %option{value: "1957"} 1957
            %option{value: "1956"} 1956
            %option{value: "1955"} 1955
            %option{value: "1954"} 1954
            %option{value: "1953"} 1953
            %option{value: "1952"} 1952
            %option{value: "1951"} 1951
            %option{value: "1950"} 1950
            %option{value: "1949"} 1949
            %option{value: "1948"} 1948
            %option{value: "1947"} 1947
            %option{value: "1946"} 1946
            %option{value: "1945"} 1945
            %option{value: "1944"} 1944
            %option{value: "1943"} 1943
            %option{value: "1942"} 1942
            %option{value: "1941"} 1941
            %option{value: "1940"} 1940
            %option{value: "1939"} 1939
            %option{value: "1938"} 1938
            %option{value: "1937"} 1937
            %option{value: "1936"} 1936
            %option{value: "1935"} 1935
            %option{value: "1934"} 1934
            %option{value: "1933"} 1933
            %option{value: "1932"} 1932
            %option{value: "1931"} 1931
            %option{value: "1930"} 1930
            %option{value: "1929"} 1929
            %option{value: "1928"} 1928
            %option{value: "1927"} 1927
            %option{value: "1926"} 1926
            %option{value: "1925"} 1925
            %option{value: "1924"} 1924
            %option{value: "1923"} 1923
            %option{value: "1922"} 1922
            %option{value: "1921"} 1921
            %option{value: "1920"} 1920
            %option{value: "1919"} 1919
            %option{value: "1918"} 1918
            %option{value: "1917"} 1917
            %option{value: "1916"} 1916
            %option{value: "1915"} 1915
            %option{value: "1914"} 1914
            %option{value: "1913"} 1913
            %option{value: "1912"} 1912
            %option{value: "1911"} 1911
            %option{value: "1910"} 1910
            %option{value: "1909"} 1909
            %option{value: "1908"} 1908
            %option{value: "1907"} 1907
            %option{value: "1906"} 1906
            %option{value: "1905"} 1905
            %option{value: "1904"} 1904
            %option{value: "1903"} 1903
            %option{value: "1902"} 1902
            %option{value: "1901"} 1901
            %option{value: "1900"} 1900
          %span.birth 年
          %select{name: "month"}
            %option{value: ""} --
            %option{value: "1"} 1
            %option{value: "2"} 2
            %option{value: "3"} 3
            %option{value: "4"} 4
            %option{value: "5"} 5
            %option{value: "6"} 6
            %option{value: "7"} 7
            %option{value: "8"} 8
            %option{value: "9"} 9
            %option{value: "10"} 10
            %option{value: "11"} 11
            %option{value: "12"} 12
          %span.birth 月
          %select{name: "day"}
            %option{value: ""} --
            %option{value: "1"} 1
            %option{value: "2"} 2
            %option{value: "3"} 3
            %option{value: "4"} 4
            %option{value: "5"} 5
            %option{value: "6"} 6
            %option{value: "7"} 7
            %option{value: "8"} 8
            %option{value: "9"} 9
            %option{value: "10"} 10
            %option{value: "11"} 11
            %option{value: "12"} 12
            %option{value: "13"} 13
            %option{value: "14"} 14
            %option{value: "15"} 15
            %option{value: "16"} 16
            %option{value: "17"} 17
            %option{value: "18"} 18
            %option{value: "19"} 19
            %option{value: "20"} 20
            %option{value: "21"} 21
            %option{value: "22"} 22
            %option{value: "23"} 23
            %option{value: "24"} 24
            %option{value: "25"} 25
            %option{value: "26"} 26
            %option{value: "27"} 27
            %option{value: "28"} 28
            %option{value: "29"} 29
            %option{value: "30"} 30
            %option{value: "31"} 31
          %span.birth 日
        %p.form-info-text
          ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
      .form-group
        %p.l-single-text.text-center
          「次へ進む」のボタンを押すことにより、
          %link_to{href: "", target: "_blank"}> 利用規約
          に同意したものとみなします
      = link_to second_registers_path , class: 'button-next' do
        %p 次へ進む
      .form-group
        %p.identify-info
          %link_to.identify{href: "", target: "_blank"}
            本人情報の登録について
            %i.fas.fa-chevron-right
      .form-group
        .privacy-policy
          %p#privacy
            This site is protected by reCAPTCHA and the Google
            %link_to{href: "", target: "_blank"} Privacy Policy
            and
            %link_to{href: "", target: "_blank"} Terms of Service
            apply.
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        %link_to{href: ""} プライバシーポリシー
      %li
        %link_to{href: ""} メルカリ利用規約
      %li
        %link_to{href: ""} 特定商取引に関する表記
  %link_to{href: "https://www.mercari.com/jp/"}
    = image_tag "/logo_gray.svg", height:'65', width:'80'
  %p
    %small © Mercari, Inc.

app/views/registers/_index_three.html.haml
%header.single-header-three
  .header-min
    %h1
      %link_to{href: ""}
        = image_tag "/fmarket_logo_red.svg", height:'50', width:'185'
    %nav
      %ol.clearfix
        %li.procedure_one
          会員情報
          %br/
          .progress-status
        %li.procedure_two
          電話番号認証
          %br/
          .progress-status
        %li.procedure_three
          お届け先住所
          %br/
          .progress-status
        %li.procedure_four
          支払い方法
          %br/
          .progress-status
        %li.procedure_five
          完了
          %br/
          .progress-status
%main.page-three
  %h2 発送元・お届け先住所入力
  %form
    -# %input{name: "", type: "hidden", value: ""}/
    .contents
      .form-content
        %label{for: "name"} お名前
        %span 必須
        %input{name: "family-name", placeholder: "例) 山田", type: "text", value: ""}/
        %input{name: "first-name", placeholder: "例) 彩", type: "text", value: ""}/
      .form-content
        %label{for: "name"} お名前カナ
        %span 必須
        %input{name: "family-name-kana", placeholder: "例) ヤマダ", type: "text", value: ""}/
        %input{name: "first-name-kana", placeholder: "例) アヤ", type: "text", value: ""}/
      .form-content
        %label{for: "zip_code1"} 郵便番号
        %span 必須
        %input{name: "zip_code1", placeholder: "例) 123-4567", type: "text", value: ""}/
      .form-content
        %label{for: "prefecture"} 都道府県
        %span 必須
        %br/
        %select{name: "prefecture"}
          %option{value: ""} --
          %option{value: "北海道"} 北海道
          %option{value: "青森県"} 青森県
          %option{value: "岩手県"} 岩手県
          %option{value: "宮城県"} 宮城県
          %option{value: "秋田県"} 秋田県
          %option{value: "山形県"} 山形県
          %option{value: "福島県"} 福島県
          %option{value: "茨城県"} 茨城県
          %option{value: "栃木県"} 栃木県
          %option{value: "群馬県"} 群馬県
          %option{value: "埼玉県"} 埼玉県
          %option{value: "千葉県"} 千葉県
          %option{value: "東京都"} 東京都
          %option{value: "神奈川県"} 神奈川県
          %option{value: "新潟県"} 新潟県
          %option{value: "富山県"} 富山県
          %option{value: "石川県"} 石川県
          %option{value: "福井県"} 福井県
          %option{value: "山梨県"} 山梨県
          %option{value: "長野県"} 長野県
          %option{value: "岐阜県"} 岐阜県
          %option{value: "静岡県"} 静岡県
          %option{value: "愛知県"} 愛知県
          %option{value: "三重県"} 三重県
          %option{value: "滋賀県"} 滋賀県
          %option{value: "京都府"} 京都府
          %option{value: "大阪府"} 大阪府
          %option{value: "兵庫県"} 兵庫県
          %option{value: "奈良県"} 奈良県
          %option{value: "和歌山県"} 和歌山県
          %option{value: "鳥取県"} 鳥取県
          %option{value: "島根県"} 島根県
          %option{value: "岡山県"} 岡山県
          %option{value: "広島県"} 広島県
          %option{value: "山口県"} 山口県
          %option{value: "徳島県"} 徳島県
          %option{value: "香川県"} 香川県
          %option{value: "愛媛県"} 愛媛県
          %option{value: "高知県"} 高知県
          %option{value: "福岡県"} 福岡県
          %option{value: "佐賀県"} 佐賀県
          %option{value: "長崎県"} 長崎県
          %option{value: "熊本県"} 熊本県
          %option{value: "大分県"} 大分県
          %option{value: "宮崎県"} 宮崎県
          %option{value: "鹿児島県"} 鹿児島県
          %option{value: "沖縄県"} 沖縄県
          %option{value: "未定"} 未定
      .form-content
        %label{for: "city"} 市区町村
        %span 必須
        %input{name: "city", placeholder: "例) 横浜市緑区", type: "text", value: ""}/
      .form-content
        %label{for: "address1"} 番地
        %span 必須
        %input{name: "address1", placeholder: "例) 青山1-1-1", type: "text", value: ""}/
      .form-content
        %label{for: "address2"} 建物名
        %span.any 任意
        %input{name: "address2", placeholder: "例) 柳ビル103", type: "text", value: ""}/
      .form-content
        %label{for: "phone"} 電話
        %span.any 任意
        %input{name: "phone", placeholder: "例) 09012345678", type: "text", value: ""}/
      = link_to forth_registers_path , class: 'button-next' do
        %p 次へ進む
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        %link_to{href: ""} プライバシーポリシー
      %li
        %link_to{href: ""} メルカリ利用規約
      %li
        %link_to{href: ""} 特定商取引に関する表記
  %link_to{href: "https://www.mercari.com/jp/"}
    = image_tag "/logo_gray.svg", height:'65', width:'80'
  %p
    %small © Mercari, Inc.

app/views/registers/_index_two.html.haml
%header.single-header-two
  .header-min
    %h1
      %link_to{href: ""}
        = image_tag "/fmarket_logo_red.svg", height:'50', width:'185'
    %nav
      %ol.clearfix
        %li.procedure_one
          会員情報
          %br/
          .progress-status
        %li.procedure_two
          電話番号認証
          %br/
          .progress-status
        %li.procedure_three
          お届け先住所
          %br/
          .progress-status
        %li.procedure_four
          支払い方法
          %br/
          .progress-status
        %li.procedure_five
          完了
          %br/
          .progress-status
%main.page-two
  %h2 電話番号の確認
  %form
    -# %input{name: "", type: "hidden", value: ""}/
    .contents
      .form-content
        %label.label-default{for: "phone_number"} 携帯電話の番号
        %input.input-default{name: "phone_number", placeholder: "携帯電話の番号を入力", type: "tel", value: ""}/
      %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
      = link_to third_registers_path , class: 'button-next' do
        %p 次へ進む
      %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
      %link_to{href: "", target: "_blank"}
        電話番号の確認が必要な理由
        %i.fas.fa-chevron-right
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        %link_to{href: ""} プライバシーポリシー
      %li
        %link_to{href: ""} メルカリ利用規約
      %li
        %link_to{href: ""} 特定商取引に関する表記
  %link_to{href: "https://www.mercari.com/jp/"}
    = image_tag "/logo_gray.svg", height:'65', width:'80'
  %p
    %small © Mercari, Inc.

app/views/registers/fifth.html.haml
=render partial: 'index_five'

app/views/registers/first.html.haml
=render partial: 'index_one'

app/views/registers/forth.html.haml
=render partial: 'index_four'

app/views/registers/index.html.haml
= link_to first_registers_path do
  メールアドレスで登録する

app/views/registers/second.html.haml
=render partial: 'index_two'

app/views/registers/third.html.haml
=render partial: 'index_three'