config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  
 


  root to: 'products#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_shipping_PayGuest', defaults: { format: 'json' }
      get 'get_shipping_PayFormer', defaults: { format: 'json' }
      get :buy_confirm
      post :purchase
      get :done
    end
  end

  get '/signup', to: "signup#index"

  resource :mypage, only: [:show] do
    collection do
      get :identification
      get :profile
      get :card
      get :logout
    end
  end


  #以下作業用およびテスト用。

  resources :tests, only: [:index, :new, :create]
  get '/tmp', to: 'tmps#index'


  resources :registers, only: [:index] do
    collection do
      get :first
      get :second
      get :third
      get :forth
      get :fifth
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :zipcode, :prefecture, :city, :district, :building, presence: true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :products
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :products
end

app/models/fromprefecture.rb
class Fromprefecture < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :description, :term_id, :size_id, :condition_id, :shipping_id, :delivery_id, :fromprefecture_id, :category_id, :user_id,  presence: true
  has_many_attached :images, dependent: :destroy

  validate :image_presence

  def image_presence
    images.attached?
  end

  belongs_to :user, optional: true
  belongs_to :brand, optional: true
  belongs_to :term, optional: true
  belongs_to :size, optional: true
  belongs_to :condition, optional: true
  belongs_to :shipping, optional: true
  belongs_to :delivery, optional: true
  belongs_to :fromprefecture, optional: true
  belongs_to :category, optional: true
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :products
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
  validates :uid,presence: true
  validates :provider,presence: true
  validates :user_id,presence: true
end

app/models/term.rb
class Term < ApplicationRecord
  has_many :products
end

app/models/test.rb
class Test < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  validates :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, presence: true
  has_one :address
  has_many :products
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :set_select, only: [:show, :identification, :profile, :card, :logout]

  def show
    
  end

  def identification
  end

  def profile
  end

  def card
  end

  def logout
  end

  private

  def set_select
    @parents = Category.all.order("id ASC").limit(14)
    @brands = Brand.all.order("id ASC").limit(8)
  end
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/tmps_helper.rb
module TmpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mypages/card.html.haml
=render partial: "layouts/header"
- breadcrumb :card

.nav-bread
  .nav-bread__nav-box
    %ul
      %li
        = breadcrumbs  separator: " &rsaquo; "

.main-background
  .main-contents

    .main-contents__left-menu
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            マイページ
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            お知らせ
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            やることリスト
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            いいね！一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品する
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-出品中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-取引中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-売却済み
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            購入した商品-取引中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            購入した商品-過去の取引
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ニュース一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            評価一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ガイド
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            お問い合わせ
          %span.right-arror
            >

      .main-contents__left-menu__menu-title
        メルペイ
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            売上・振込申請
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ポイント
          %span.right-arror
            >

      .main-contents__left-menu__menu-title
        設定
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            プロフィール
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            発送元・お届け先住所変更
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side logout" do
          %span
            支払い方法
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            メール/パスワード
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            本人情報
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            電話番号の確認
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ログアウト
          %span.right-arror
            >
    
    .card-box
      .card-box__card-top
        .card-box__card-top__card-inside
          %span
            支払い方法
      .card-box__card-content
        .card-box__card-content__card-text
          %p
            クレジットカード一覧
        .card-box__card-content__card-button
          = link_to "#" do
            %i.far.fa-credit-card
            クレジットカードを追加する

        .card-box__card-content__card-link
          .bottom_wrap
            = link_to "#" do
              支払い方法について ＞



=render partial: "layouts/button"
=render partial: "layouts/banner-bottom"
=render partial: "layouts/footer"

app/views/mypages/identification.html.haml
=render partial: "layouts/header"
- breadcrumb :identification

.nav-bread
  .nav-bread__nav-box
    %ul
      %li
        = breadcrumbs  separator: " &rsaquo; "


.main-background
  .main-contents
  
    .main-contents__left-menu
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            マイページ
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            お知らせ
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            やることリスト
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            いいね！一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品する
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-出品中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-取引中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-売却済み
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            購入した商品-取引中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            購入した商品-過去の取引
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ニュース一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            評価一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ガイド
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            お問い合わせ
          %span.right-arror
            >

      .main-contents__left-menu__menu-title
        メルペイ
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            売上・振込申請
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ポイント
          %span.right-arror
            >

      .main-contents__left-menu__menu-title
        設定
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            プロフィール
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            発送元・お届け先住所変更
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            支払い方法
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            メール/パスワード
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side logout" do
          %span
            本人情報
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            電話番号の確認
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ログアウト
          %span.right-arror
            >
    



    .id-box
      .id-box__id-top
        .id-box__id-top__id-inside
          %span
            本人情報の登録
        %form 
          %div
            %p
              お客さまの本人情報をご登録ください。
              <br>登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            %p.right
              = link_to "本人確認書類のアップロードについて>", "#"
          .form-group
            %label
              お名前
            %p
              ××××
          .form-group
            %label
              お名前カナ
            %p
              △△△△
          .form-group
            %label{for: "birthday"} 
              生年月日
            %p
              2020/01/01
          
          .form-group
            %label{for: "zip_code"} 
              郵便番号
            %span
              任意
            %input{name: "zip_code", placeholder: "例）1234567", type: "text"}/

          .form-group
            %label{for: "prefecture"} 
              都道府県
            %span
              任意
            .prefecture-wrap
              %i.fas.fa-chevron-down
              %select{name: "prefecture"}
                %option{value: ""} --
                %option{value: "北海道"} 北海道
                %option{value: "青森県"} 青森県
                %option{value: "岩手県"} 岩手県
                %option{value: "宮城県"} 宮城県
                %option{value: "宮城県"} 秋田県
                %option{value: "山形県"} 山形県
                %option{value: "福島県"} 福島県
                %option{value: "茨城県"} 茨城県
                %option{value: "栃木県"} 栃木県
                %option{value: "群馬県"} 埼玉県
                %option{value: "千葉県"} 東京都
                %option{value: "神奈川県"} 神奈川県
                %option{value: "新潟県"} 新潟県
                %option{value: "富山県"} 富山県
                %option{value: "石川県"} 石川県
                %option{value: "福井県"} 福井県
                %option{value: "山梨県"} 山梨県
                %option{value: "長野県"} 長野県
                %option{value: "岐阜県"} 岐阜県
                %option{value: "静岡県"} 静岡県
                %option{value: "愛知県"} 愛知県
                %option{value: "三重県"} 三重県
                %option{value: "滋賀県"} 滋賀県
                %option{value: "京都府"} 京都府
                %option{value: "大阪府"} 大阪府
                %option{value: "兵庫県"} 兵庫県
                %option{value: "奈良県"} 奈良県
                %option{value: "和歌山県"} 和歌山県
                %option{value: "鳥取県"} 鳥取県
                %option{value: "島根県"} 島根県
                %option{value: "岡山県"} 岡山県
                %option{value: "広島県"} 広島県
                %option{value: "山口県"} 山口県
                %option{value: "徳島県"} 香川県
                %option{value: "愛媛県"} 愛媛県
                %option{value: "高知県"} 高知県
                %option{value: "福岡県"} 福岡県
                %option{value: "佐賀県"} 佐賀県
                %option{value: "長崎県"} 長崎県
                %option{value: "熊本県"} 熊本県
                %option{value: "大分県"} 大分県
                %option{value: "宮崎県"} 宮崎県
                %option{value: "鹿児島県"} 鹿児島県
                %option{value: "沖縄県"} 沖縄県

            .form-group
              %label{for: "city"} 
                市区町村 
              %span
                任意
              %input{name: "city", placeholder: "例）横浜市緑区", type: "text"}/

            .form-group
              %label{for: "address1_label"} 
                番地 
              %span
                任意
              %input{name: "address1", placeholder: "例）青山1-1-1", type: "text"}/

            .form-group
              %label{for: "address2_label"} 
                建物名 
              %span
                任意
              %input{name: "address2", placeholder: "例）柳ビル103", type: "text"}/

            %button{type: "submit"}
              登録する

            %p.right
              = link_to "本人情報の登録について>", "#"

      .id-box__id-content


=render partial: "layouts/button"
=render partial: "layouts/banner-bottom"
=render partial: "layouts/footer"

app/views/mypages/logout.html.haml
=render partial: "layouts/header"
- breadcrumb :logout

.nav-bread
  .nav-bread__nav-box
    %ul
      %li
        = breadcrumbs  separator: " &rsaquo; "


.main-background
  .main-contents
    = render partial: 'layouts/left-menu'
    


    .main-contents__right-box
      .main-contents__right-box__right-inner
        .main-contents__right-box__right-inner__right-logout
          = link_to destroy_user_session_path, method: :delete, class: "link-logout" do
            ログアウト


=render partial: "layouts/button"
=render partial: "layouts/banner-bottom"
=render partial: "layouts/footer"

app/views/mypages/profile.html.haml
=render partial: "layouts/header"
- breadcrumb :profile

.nav-bread
  .nav-bread__nav-box
    %ul
      %li
        = breadcrumbs  separator: " &rsaquo; "


.main-background
  .main-contents

    .main-contents__left-menu
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            マイページ
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            お知らせ
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            やることリスト
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            いいね！一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品する
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-出品中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-取引中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-売却済み
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            購入した商品-取引中
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            購入した商品-過去の取引
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ニュース一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            評価一覧
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ガイド
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            お問い合わせ
          %span.right-arror
            >

      .main-contents__left-menu__menu-title
        メルペイ
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            売上・振込申請
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ポイント
          %span.right-arror
            >

      .main-contents__left-menu__menu-title
        設定
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side logout" do
          %span
            プロフィール
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            発送元・お届け先住所変更
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            支払い方法
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            メール/パスワード
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            本人情報
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            電話番号の確認
          %span.right-arror
            >
      .main-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ログアウト
          %span.right-arror
            >


    .profile-box
      .profile-box__profile-top
        .profile-box__profile-top__profile-inside
          %span
            プロフィール
      %form
        .profile-icon
          %figure
            = image_tag "/profile_person1.jpg", size: "60x60", alt: "プロフィール画像"
          %input{ type: "text", value: "" , name: "nickname", placeholder: "例）AYA☆セール中"}
        .profile-content
          %textarea{ name: "introduction", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}

          %button
            変更する






=render partial: "layouts/button"
=render partial: "layouts/banner-bottom"
=render partial: "layouts/footer"

app/views/mypages/show.html.haml
=render partial: "layouts/header"
- breadcrumb :mypage


.mypage-nav
  .mypage-nav__nav-box
    %ul
      %li
        = breadcrumbs  separator: " &rsaquo; "
          


.mypage-background
  .mypage-contents
    .mypage-contents__left-menu
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side mypage" do
          %span
            マイページ
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            お知らせ
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            やることリスト
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            いいね！一覧
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品する
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-出品中
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-取引中
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            出品した商品-売却済み
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            購入した商品-取引中
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            購入した商品-過去の取引
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ニュース一覧
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            評価一覧
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ガイド
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            お問い合わせ
          %span.right-arror
            >

      .mypage-contents__left-menu__menu-title
        メルペイ
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            売上・振込申請
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            ポイント
          %span.right-arror
            >

      .mypage-contents__left-menu__menu-title
        設定
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            プロフィール
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            発送元・お届け先住所変更
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            支払い方法
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            メール/パスワード
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            本人情報
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to "#", class: "side" do
          %span
            電話番号の確認
          %span.right-arror
            >
      .mypage-contents__left-menu__menu-each
        = link_to logout_mypage_path, class: "side" do
          %span
            ログアウト
          %span.right-arror
            >
    
    .mypage-contents__right-menu
      .mypage-contents__right-menu__user-icon
        = link_to "#" ,class: "information" do
          %img{height: "60", width: "60", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsbPo7e-3mJmSToduD9rn2jQKOePe2TOCqyfGndSJeDuR39rbOyQ&s"}
          %h2 テストユーザー
          .mypage-number
            .mypage-number__left-number
              評価
              %span 0
            .mypage-number__right-number
              出品数
              %span 0

      .mypage-contents__right-menu__top-container
        .mypage-top-tab
          %ul
            %li
              = link_to "#tab_1", class:"menu select" do
                %h3 お知らせ
            %li
              = link_to "#tab_2", class: "menu" do
                %h3 やることリスト
        .mypage-top-notification#tab_1.current
          %ul
            %li
              = link_to "#", class: "link" do
                %img{height: "48", width: "48", src: "https://iconbu.com/wp-content/uploads/2019/09/01-12.png"}/
                
                .notification-body
                  .notification-text
                    《この通知を受け取ったあなた限定》¥1,000の商品を「実質1円」でご購入いただけます！
                  .time
                    %i.far.fa-clock
                    %span ９時間前
                .right-arrow    
                  %i.fas.fa-chevron-right

            %li
              = link_to "#", class: "link" do
                %img{height: "48", width: "48", src: "https://iconbu.com/wp-content/uploads/2019/09/01-12.png"}/
                
                .notification-body
                  .notification-text
                    《この通知を受け取ったあなた限定》¥1,000の商品を「実質1円」でご購入いただけます！
                  .time
                    %i.far.fa-clock
                    %span 16時間前
                .right-arrow    
                  %i.fas.fa-chevron-right

            %li
              = link_to "#", class: "link" do
                %img{height: "48", width: "48", src: "https://iconbu.com/wp-content/uploads/2019/09/01-12.png"}/
                
                .notification-body
                  .notification-text
                    《この通知を受け取ったあなた限定》¥1,000の商品を「実質1円」でご購入いただけます！
                  .time
                    %i.far.fa-clock
                    %span 2日前
                .right-arrow    
                  %i.fas.fa-chevron-right


            %li.mypage-go-list
              = link_to "#", class: "link" do
                %span 一覧へ戻る


        .mypage-top-notification#tab_2
          %ul
            %li
              = link_to "#", class: "link" do
                %img{height: "48", width: "48", src: "https://iconbu.com/wp-content/uploads/2019/09/01-12.png"}/
                
                .notification-body
                  .notification-text
                    ご登録のメールアドレスに認証メールを送りました。メールに記載のURLをクリックして、メールアドレスを認証してください。
                  .time
                    %i.far.fa-clock
                    %span ９時間前
                .right-arrow    
                  %i.fas.fa-chevron-right

            %li.mypage-go-list
              = link_to "#", class: "link" do
                %span 一覧へ戻る


      .mypage-contents__right-menu__bottom-container
        %h2 購入した商品
        .mypage-bottom-tab
          %ul
            %li
              = link_to "#tab_3",class:"tab active" do
                %h3 取引中
            %li
              = link_to "#tab_4",class:"tab" do
                %h3 過去の取引

        .mypage-bottom-panel
          .not-found#tab_3.show
            .not-text-logo
            %span 取引中の商品がありません

          .not-found#tab_4
            .not-text-logo
            %span 過去の取引はありません


=render partial: "layouts/button"
=render partial: "layouts/banner-bottom"
=render partial: "layouts/footer"