config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  
 


  root to: 'products#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_shipping_PayGuest', defaults: { format: 'json' }
      get 'get_shipping_PayFormer', defaults: { format: 'json' }
      get :buy_confirm
      post :purchase
      get :done
    end
  end

  get '/signup', to: "signup#index"

  resource :mypage, only: [:show] do
    collection do
      get :identification
      get :profile
      get :card
      get :logout
    end
  end


  #以下作業用およびテスト用。

  resources :tests, only: [:index, :new, :create]
  get '/tmp', to: 'tmps#index'


  resources :registers, only: [:index] do
    collection do
      get :first
      get :second
      get :third
      get :forth
      get :fifth
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :zipcode, :prefecture, :city, :district, :building, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :products
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :products
end

app/models/fromprefecture.rb
class Fromprefecture < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :description, :term_id, :size_id, :condition_id, :shipping_id, :delivery_id, :fromprefecture_id, :category_id, :user_id,  presence: true
  has_many_attached :images, dependent: :destroy

  validate :image_presence

  def image_presence
    images.attached?
  end

  belongs_to :user, optional: true
  belongs_to :brand, optional: true
  belongs_to :term, optional: true
  belongs_to :size, optional: true
  belongs_to :condition, optional: true
  belongs_to :shipping, optional: true
  belongs_to :delivery, optional: true
  belongs_to :fromprefecture, optional: true
  belongs_to :category, optional: true
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :products
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
  validates :uid,presence: true
  validates :provider,presence: true
  validates :user_id,presence: true
end

app/models/term.rb
class Term < ApplicationRecord
  has_many :products
end

app/models/test.rb
class Test < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  validates :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, presence: true
  has_one :address
  has_many :products
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :redirect_root, only: [:buy_confirm]
  before_action :set_product, only: [:show, :edit, :update, :purchase, :destroy]
  before_action :set_select, only: [:index, :show]

  require 'payjp'

  def index
    @product = Product.all


    #レディース
    nums_ladies = Category.where(ancestry: '1/15').or(Category.where(ancestry: '1/16')).or(Category.where(ancestry: '1/17')).or(Category.where(ancestry: '1/18')).or(Category.where(ancestry: '1/19')).or(Category.where(ancestry: '1/20')).ids
    @ladies = Product.where(category_id: nums_ladies).order("created_at DESC").limit(10)
    

    #メンズ
    nums_mens = Category.where(ancestry: '2/80').or(Category.where(ancestry: '2/81')).or(Category.where(ancestry: '2/82')).or(Category.where(ancestry: '2/83')).or(Category.where(ancestry: '2/84')).ids
    @mens = Product.where(category_id: nums_mens).order("created_at DESC").limit(10)

    
    #家電・スマホ
    nums_elecs = Category.where(ancestry: '8/398').or(Category.where(ancestry: '8/399')).or(Category.where(ancestry: '8/400')).or(Category.where(ancestry: '8/401')).ids
    @elecs = Product.where(category_id: nums_elecs).order("created_at DESC").limit(10)


    #おもちゃ、ホビー
    nums_toys = Category.where(ancestry: '6/295').or(Category.where(ancestry: '6/296')).or(Category.where(ancestry: '6/297')).or(Category.where(ancestry: '6/298')).or(Category.where(ancestry: '6/299')).ids
    @toys = Product.where(category_id: nums_toys).order("created_at DESC").limit(10)


    #シャネル
    @chanel = Product.where(brand_id: 1).limit(10).order(created_at: "DESC")

    #ルイヴィトン
    @vuittons = Product.where(brand_id: 3).limit(10).order(created_at: "DESC")

    #ナイキ
    @nikes = Product.where(brand_id: 6).limit(10).order(created_at: "DESC")

    #シュプリーム
    @supremes = Product.where(brand_id: 4).limit(10).order(created_at: "DESC")

  end

  def show
    @other_brands = Product.where(brand_id: @product.brand_id).where.not(id: @product.id)
    @other_myproducts = Product.where(user_id: @product.user_id).where.not(id: @product.id)

  end

  def new
    @product = Product.new
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
 end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def get_shipping_PayFormer
    @shipping_payformer = Shipping.all
  end

  def get_shipping_PayGuest
    @shipping_payguest = Shipping.find(1,6,7,3)
  end


  def create
    @product = Product.new(create_params)
    @product.save!
  end

  def edit
  end

  def update
    if @product.update(create_params)
      render "update"
    else
      render "edit"
    end
  end

  def destroy
    if @product.destroy
      render "delete"
    else
      redirect_to product_path
    end
  end
  

  def buy_confirm
    @product = Product.find(params[:format])
  end

  def purchase
    Payjp.api_key = ENV['PAYJP_ACCESS_KEY']
    Payjp::Charge.create(
      amount: @product.price,
      card: params['payjp-token'],
      currency: 'jpy'
    )
    @product.update(buyer_id: current_user.id)
    redirect_to done_products_path
  end

  def done
  end


  private
  def create_params
    params.require(:product).permit(:name, :description, :condition_id, :term_id, :delivery_id, :shipping_id, :category_id, :fromprefecture_id, :price, :size_id, :brand_id,:_destroy ,images: []).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_select
    @parents = Category.all.order("id ASC").limit(14)
    @brands = Brand.all.order("id ASC").limit(8)
  end
  
  def redirect_root
    redirect_to root_path unless user_signed_in?
  end
  
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/tmps_helper.rb
module TmpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_banner-top.html.haml
.banners
  =link_to "https://www.mercari.com/jp/" do
    .banner__top
      .banner__top__contents
        =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/top-banner-main-device-1f627e51e488f6ca35feaa6a08b79736.png",class:"phone-image"
        .banner__top__contents__area
          .banner__top__contents__area__title
            スマホで
            かんたん
            %br
            フリマアプリ
          %p.banner__top__contents__area__text
            Fmarketはスマホカメラからすぐに出品できる
            %br
            購入時も安心な独自システムアプリです
          .banner__top__contents__area__stores
            %object
              =link_to "https://www.mercari.com/jp/" do
                =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg", height: "50", width: "170"
            %object
              =link_to "https://www.mercari.com/jp/" do
                =image_tag "https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg", height: "50", width: "170"
      .banner__top__arrow-left
        %i.fas.fa-chevron-left
      .banner__top__arrow-right
        %i.fas.fa-chevron-right

app/views/products/_contents.html.haml
.popular
  %h2 人気のカテゴリー
  .popular__lists
    %ul
      %li
        = link_to "#" do
          レディース
      %li
        = link_to "#" do
          メンズ
      %li
        = link_to "#" do
          家電・スマホ・カメラ
      %li
        = link_to "#" do
          おもちゃ・ホビー・グッズ


.main-contents
  .main-contents__lists
    .main-contents__lists__head
      %h3 レディース新着アイテム
      = link_to "#" do
        もっと見る
        %i.fas.fa-chevron-right
    .main-contents__lists__bodys
      .main-contents__lists__bodys__body
        %ul.items
          =render partial: "products/category/ladies"
          


  .main-contents__lists
    .main-contents__lists__head
      %h3 メンズ新着アイテム
      = link_to "#" do
        もっと見る
        %i.fas.fa-chevron-right
    .main-contents__lists__bodys
      .main-contents__lists__bodys__body
        %ul.items
          =render partial: "products/category/mens"

  .main-contents__lists
    .main-contents__lists__head
      %h3 家電・スマホ・カメラ新着アイテム
      = link_to "#" do
        もっと見る
        %i.fas.fa-chevron-right
    .main-contents__lists__bodys
      .main-contents__lists__bodys__body
        %ul.items
          =render partial: "products/category/elecs"

  .main-contents__lists
    .main-contents__lists__head
      %h3 おもちゃ・ホビー・グッズ新着アイテム
      = link_to "#" do
        もっと見る
        %i.fas.fa-chevron-right
    .main-contents__lists__bodys
      .main-contents__lists__bodys__body
        %ul.items
          =render partial: "products/category/toys"


.popular
  %h2 人気のブランド
  .popular__lists
    %ul
      %li
        = link_to "#" do
          シャネル
      %li
        = link_to "#" do
          ルイヴィトン
      %li
        = link_to "#" do
          シュプリーム
      %li
        = link_to "#" do
          ナイキ

.main-contents
  .main-contents__lists
    .main-contents__lists__head
      %h3 シャネル
      = link_to "#" do
        もっと見る
        %i.fas.fa-chevron-right
    .main-contents__lists__bodys
      .main-contents__lists__bodys__body
        %ul.items
          =render partial: "products/category/chanel"

  .main-contents__lists
    .main-contents__lists__head
      %h3 ルイヴィトン
      = link_to "#" do
        もっと見る
        %i.fas.fa-chevron-right
    .main-contents__lists__bodys
      .main-contents__lists__bodys__body
        %ul.items
          =render partial: "products/category/vuittons"

    .main-contents__lists
      .main-contents__lists__head
        %h3 シュプリーム
        = link_to "#" do
          もっと見る
          %i.fas.fa-chevron-right
      .main-contents__lists__bodys
        .main-contents__lists__bodys__body
          %ul.items
            =render partial: "products/category/supremes"

      .main-contents__lists
        .main-contents__lists__head
          %h3 ナイキ
          = link_to "#" do
            もっと見る
            %i.fas.fa-chevron-right
        .main-contents__lists__bodys
          .main-contents__lists__bodys__body
            %ul.items
              =render partial: "products/category/nikes"

app/views/products/_edit.html.haml
=link_to edit_product_path(@product.id) , class:"edit-btn" do
  編集する

app/views/products/_items.html.haml
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い

          
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://cdn.thumb.shop-list.com/res/up/shoplist/shp/__basethum900__/decorative/2ta/2ta003-11.jpg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://arine.akamaized.net/uploads/photo/upload_photo/data/355872/large_b241da6c-41e5-4f25-b4f8-3c63d5dd210c.jpeg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://cdn.thumb.shop-list.com/res/up/shoplist/shp/__basethum900__/decorative/2ta/2ta003-11.jpg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://arine.akamaized.net/uploads/photo/upload_photo/data/355872/large_b241da6c-41e5-4f25-b4f8-3c63d5dd210c.jpeg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://o.imgz.jp/fashionnews/105709/cwhi5n7qwwrabxq.jpg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://cdn.thumb.shop-list.com/res/up/shoplist/shp/__basethum900__/decorative/2ta/2ta003-11.jpg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い
%li.item
  .item__details
    %a{ href: "/"}
      %figure
        .item-image
          %span ¥30,000
          =image_tag "https://arine.akamaized.net/uploads/photo/upload_photo/data/355872/large_b241da6c-41e5-4f25-b4f8-3c63d5dd210c.jpeg"
        %figcaption
          %span そこらへんで拾ってきた画像だからなんのこっちゃしらんけど可愛い

app/views/products/buy_confirm.html.haml
.confirm-contents
  .confirm-contents__confirm-header
    %svg{:viewbox => "0 0 281.19 84.08", :xmlns => "http://www.w3.org/2000/svg", width: "180", height: "50"}
      %defs
        :css
          .cls-1{fill:#fff;stroke:#b53d22;stroke-miterlimit:10;}.cls-2{font-size:40px;fill:#231815;font-family:YuGo-Bold-83pv-RKSJ-H, YuGothic;}
      %title アセット 1
      %g{"data-name" => "レイヤー 2", :id => "レイヤー_2"}
        %g{"data-name" => "レイヤー 1", :id => "レイヤー_1-2"}
          %polygon.cls-1{:points => "36.41 83.5 0.5 62.77 0.5 21.31 36.41 0.58 72.32 21.31 72.32 62.77 36.41 83.5"}
          %polyline.cls-1{:points => "0.5 21.31 36.41 42.04 72.32 21.31"}
          %polyline.cls-1{:points => "36.41 83.5 36.41 49.36 36.41 42.04"}
          %line.cls-1{:x1 => "36.41", :x2 => "0.5", :y1 => "52.41", :y2 => "31.67"}
          %line.cls-1{:x1 => "72.32", :x2 => "36.41", :y1 => "33.2", :y2 => "50.88"}
          %text.cls-2{:transform => "translate(86.41 62.77)"} Fmarket


  .confirm-contents__confirm-main
    .confirm-contents__confirm-main__confirm-title
      %p
        購入内容の確認

    .confirm-contents__confirm-main__confirm-product
      .product-box
        .product-box__product-image
          - if @product.images.attached?
            = image_tag @product.images.first , width: "70px", height: "70px"
        .product-box__product-texts
          .product-box__product-texts__product-name
            = @product.name
          .product-box__product-texts__product-price
            %span
              ¥
              = @product.price
            %span
              （税込）送料込み

    .confirm-contents__confirm-main__confirm-info
      .paying-contents
        .paying-contents__paying-box
          .paying-contents__paying-box__paying-price
            .price-left
              支払い金額
            .price-right
              %span
                ¥
                = @product.price
          .paying-contents__paying-box__paying-point
            %i.fas.fa-square
            %span
              ポイントを使用 (所持ポイント: P0)

        .paying-contents__paying-how
          .text-how
            支払い方法
          .text-register
            = link_to "#" do
              %i.fas.fa-plus-circle
              登録してください

        .paying-contents__paying-delivery
          .paying-contents__paying-delivery__paying-text
            .text-left
              発送先
            .text-right
              = link_to "#" do
                変更する

          .paying-contents__paying-delivery__paying-address
            %p
              〒
              = current_user.address.zipcode
              %br
              = current_user.address.prefecture
              = current_user.address.city
              %br
              = current_user.last_name
              = current_user.first_name

        
        = form_with url: purchase_products_path(id: @product.id) do
          :plain
            <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="pk_test_aae084f90697dd1cf39b6a02"></script>






  .confirm-contents__confirm-footer
    .footer-contents
      .footer-contents__footer-texts
        .text-left
          = link_to "#" do
            プライバシーポリシー
        .text-center
          = link_to "#" do
            メルカリ利用規約
        .text-right
          = link_to "#" do
            特定商取引に関する表記

      .footer-contents__footer-logo
        %svg{:viewbox => "0 0 147.09 129.96", :xmlns => "http://www.w3.org/2000/svg", width: "80", height: "68"}
          %defs
            :css
              .cls-1,.cls-2{fill:#231815;stroke-miterlimit:10;opacity:0.19;}.cls-1{stroke:#fff;}.cls-2{font-size:36px;stroke:#231815;font-family:YuGo-Bold-83pv-RKSJ-H, YuGothic;}
          %title アセット 13
          %g{"data-name" => "レイヤー 2", :id => "レイヤー_2"}
            %g{"data-name" => "レイヤー 1", :id => "レイヤー_1-2"}
              %polygon.cls-1{:points => "71.54 83.5 35.63 62.77 35.63 21.31 71.54 0.58 107.45 21.31 107.45 62.77 71.54 83.5"}
              %polyline.cls-1{:points => "35.63 21.31 71.54 42.04 107.45 21.31"}
              %polyline.cls-1{:points => "71.54 83.5 71.54 49.36 71.54 42.04"}
              %line.cls-1{:x1 => "71.54", :x2 => "35.63", :y1 => "52.41", :y2 => "31.67"}
              %line.cls-1{:x1 => "107.45", :x2 => "71.54", :y1 => "33.2", :y2 => "50.88"}
              %text.cls-2{:transform => "translate(0.5 117.04)"} Fmarket

      .footer-contents__footer-rights
        © Mercari, Inc.

app/views/products/done.html.haml
.confirm-contents
  .confirm-contents__confirm-header
    %svg{:viewbox => "0 0 281.19 84.08", :xmlns => "http://www.w3.org/2000/svg", width: "180", height: "50"}
      %defs
        :css
          .cls-1{fill:#fff;stroke:#b53d22;stroke-miterlimit:10;}.cls-2{font-size:40px;fill:#231815;font-family:YuGo-Bold-83pv-RKSJ-H, YuGothic;}
      %title アセット 1
      %g{"data-name" => "レイヤー 2", :id => "レイヤー_2"}
        %g{"data-name" => "レイヤー 1", :id => "レイヤー_1-2"}
          %polygon.cls-1{:points => "36.41 83.5 0.5 62.77 0.5 21.31 36.41 0.58 72.32 21.31 72.32 62.77 36.41 83.5"}
          %polyline.cls-1{:points => "0.5 21.31 36.41 42.04 72.32 21.31"}
          %polyline.cls-1{:points => "36.41 83.5 36.41 49.36 36.41 42.04"}
          %line.cls-1{:x1 => "36.41", :x2 => "0.5", :y1 => "52.41", :y2 => "31.67"}
          %line.cls-1{:x1 => "72.32", :x2 => "36.41", :y1 => "33.2", :y2 => "50.88"}
          %text.cls-2{:transform => "translate(86.41 62.77)"} Fmarket

.done-box

  %h1
    ご購入有り難うございます。
    %br
  = link_to root_path do
    トップページへ戻る

app/views/products/index.html.haml
=render partial: "layouts/header"
=render partial: "products/banner-top"
=render partial: "products/contents"
=render partial: "layouts/button"
=render partial: "layouts/banner-bottom"
=render partial: "layouts/footer"

app/views/products/show.html.haml
-# 商品詳細ぺージ

=render partial: "layouts/header"

.detail-container
  %h1
    = @product.name
    - if user_signed_in? && current_user.id == @product.user_id
      %i.fas.fa-chevron-right
        =link_to '編集する', edit_product_path(@product.id) , class:"edit-btn" 
        = link_to '削除', product_path(@product), method: :delete, class:"delete-btn"



  .detail-container__ditail-wrap

    .imagebox-left
      .imagebox-left__imagebox-large

        - if @product.images.attached?
          - @product.images.each do |image|
            = image_tag image, width: "300", height: "225", class: "inactive"
            


        - if @product.images.attached?
          - @product.images.each do |image|
            = image_tag image, width: "300", width: "300", height: "225", class: "inactive"
            %br/


      .imagebox-left__imagebox-bottom
        - if @product.images.attached?
          - @product.images.each do |image|
            = image_tag image, width: "60", height: "60", class: 'small-view'
            %br/



    %table.table-detail
      %tbody.tbody-detail
        %tr.tr-detail
          %th.th-name
            出品者
          %td
            = link_to "#" do
              = @product.user.nickname
            .face-icon
              %span
                %i.fas.fa-grin.icon-grin
                0
              %span
                %i.fas.fa-meh.icon-meh
                0
              %span
                %i.fas.fa-frown.icon-frown
                0



        %tr.tr-detail
          %th.th-category
            カテゴリー
          %td.td-category
            = link_to "#" do
              = @product.category.parent.parent.name
            = link_to "#" do
              >
              = @product.category.parent.name
            = link_to "#" do
              >
              = @product.category.name

        %tr.tr-detail
          %th.others
            ブランド
          %td
            = link_to "#" do
              = @product.brand.name

        %tr.tr-detail
          %th.others
            商品の状態
          %td
            = @product.condition.name

        %tr.tr-detail
          %th.others
            発送料の負担
          %td
            = @product.delivery.name

        %tr.tr-detail
          %th.others
            発送の方法
          %td
            = @product.shipping.name

        %tr.tr-detail
          %th.others
            発送元地域
          %td
            = link_to "#" do
              = @product.fromprefecture.name
        %tr.tr-detail
          %th.others
            発送の目安
          %td
            = @product.term.name

  .price-box
    %span.price
      ¥
      = @product.price
    %span.tax
      (税込)
    %span.deliver
      送料込み

  = link_to buy_confirm_products_path(@product), class: "next-box" do
    購入画面に進む
  .item-description
    %p
      = @product.description

  .button-container
    .button-container__button-two
      .button-container__button-two__button-like
        = link_to "#" do
          %i.far.fa-heart
          いいね! 0

      .button-container__button-two__button-report
        = link_to "#" do
          %i.fas.fa-flag-checkered
          不適切な商品の報告

    = link_to "#", class: "button-secure" do
      あんしん・あんぜんへの取り組み


     

.comment-container
  %p
    相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
  %textarea
  %button
    %span.submit-comment
      コメントする

.middle-link
  = link_to "#" do
    < 薬用シュミテクト 歯周病ケア 試供品10個
  = link_to "#" do
    長財布 >

.icons-box
  .icons-box__icons-three
    = link_to "#", class: "fb-icon" do
      %i.fab.fa-facebook-square.fa-3x
    = link_to "#", class: "twitter-icon" do
      %i.fab.fa-twitter-square.fa-3x
    = link_to "#", class: "pint-icon" do
      %%i.fab.fa-pinterest-square.fa-3x

%section.other-sell
  = link_to "#", class: "seller-name" do
    ○○さんのその他の出品
  .wrapper
    =render partial: "products/category/other_myproducts"


-# ここから、「その他の関連商品」
%section.other-sell
  = link_to "#", class: "relation-name" do
    ブランドのその他の商品
  .wrapper
    =render partial: "products/category/other_brands"



=render partial: "layouts/banner-bottom"
=render partial: "layouts/footer"