config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  
 


  root to: 'products#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'get_shipping_PayGuest', defaults: { format: 'json' }
      get 'get_shipping_PayFormer', defaults: { format: 'json' }
      get :buy_confirm
      post :purchase
      get :done
    end
  end

  get '/signup', to: "signup#index"

  resource :mypage, only: [:show] do
    collection do
      get :identification
      get :profile
      get :card
      get :logout
    end
  end


  #以下作業用およびテスト用。

  resources :tests, only: [:index, :new, :create]
  get '/tmp', to: 'tmps#index'


  resources :registers, only: [:index] do
    collection do
      get :first
      get :second
      get :third
      get :forth
      get :fifth
    end
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :zipcode, :prefecture, :city, :district, :building, presence: true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :products
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :products
end

app/models/fromprefecture.rb
class Fromprefecture < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :description, :term_id, :size_id, :condition_id, :shipping_id, :delivery_id, :fromprefecture_id, :category_id, :user_id,  presence: true
  has_many_attached :images, dependent: :destroy

  validate :image_presence

  def image_presence
    images.attached?
  end

  belongs_to :user, optional: true
  belongs_to :brand, optional: true
  belongs_to :term, optional: true
  belongs_to :size, optional: true
  belongs_to :condition, optional: true
  belongs_to :shipping, optional: true
  belongs_to :delivery, optional: true
  belongs_to :fromprefecture, optional: true
  belongs_to :category, optional: true
end

app/models/shipping.rb
class Shipping < ApplicationRecord
  has_many :products
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
  validates :uid,presence: true
  validates :provider,presence: true
  validates :user_id,presence: true
end

app/models/term.rb
class Term < ApplicationRecord
  has_many :products
end

app/models/test.rb
class Test < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  validates :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, presence: true
  has_one :address
  has_many :products
  has_many :sns_credentials

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/tmps_helper.rb
module TmpsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_banner-bottom.html.haml
.banners
  .banner__bottom
    .banner__bottom__contents
      %img.download-image{src: "https://web-jp-assets.mercdn.net/_next/static/images/download_app_pc-a4418175e8be071827ac88d073f40e4a.png"}/
      .banner__bottom__contents__area
        .banner__bottom__contents__area__title
          %h3 スマホでかんたんフリマアプリ
        .banner__bottom__contents__area__text
          %h3 今すぐ無料ダウンロード！
        .banner__bottom__contents__area__stores 
          = image_tag "/logo_red.svg", height:'70', width:'70'

          = link_to "https://www.mercari.com/jp/", class:"apple" do
            %img{height: "43", width: "150", src: "https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg"}/
          = link_to "https://www.mercari.com/jp/", class:"google" do
            %img{height: "43", width: "150", src: "https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg"}/

app/views/layouts/_button.html.haml
= link_to new_product_path ,class: "exhibition-button" do
  .exhibition-button__btn 出品
  %i.fas.fa-camera

app/views/layouts/_footer.html.haml
%footer.footer
  %nav.footer-top
    .footer-top__menu
      .footer-top__menu__first
        %ul
          %h2.footer-head Fmarketについて
          %li
            = link_to "#" do
              %span 会社概要（運営会社）
          %li
            = link_to "#" do
              %span 採用情報
          %li
            = link_to "#" do
              %span プレスリリース
          %li
            = link_to "#" do
              %span 公式ブログ
          %li
            = link_to "#" do
              %span Fmarketロゴ利用ガイドライン
          %li.footer-social-link
            = link_to "#" do
              %i.fab.fa-twitter
          %li.footer-social-link
            = link_to "#" do
              %i.fab.fa-facebook-square
      .footer-top__menu__second
        %ul
          %h2.footer-head ヘルプ＆ガイド
          %li
            = link_to "#" do
              %span ガイド
          %li
            = link_to "#" do
              %span らくらく便
          %li
            = link_to "#" do
              %span ゆうゆう便
          %li
            = link_to "#" do
              %span 大型便
          %li
            = link_to "#" do
              %span 車体取引ガイド
          %li
            = link_to "#" do
              %span あんしん・あんぜん宣言！
          %li
            = link_to "#" do
              %span 偽ブランド品撲滅への取り組み
          %li
            = link_to "#" do
              %span ボックス
      .footer-top__menu__third
        %h2.footer-head プライバシーと利用規約
        .footer-top__menu__third__lists
          %ul.left
            %li
              = link_to "#" do
                %span プライバシーポリシー
            %li
              = link_to "#" do
                %span 利用規約
            %li
              = link_to "#" do
                %span あんしんスマホサポート制度に関する利用特約
            %li
              = link_to "#" do
                %span コンプライアンスポリシー
          %ul.right
            %li
              = link_to "#" do
                %span 個人データの安全管理に係る基本方針
            %li
              = link_to "#" do
                %span 特定商取引に関する表記
            %li
              = link_to "#" do
                %span 資金決済法に基づく基づく表示
            %li
              = link_to "#" do
                %span 法令順守と犯罪防止のために
      .footer-top__menu__fourth
        %ul
          %h2.footer-head 国
          %li
            = link_to "#" do
              %span 日本
          %li
            = link_to "#" do
              %span United States
      %ul
  .footer-row
    = link_to "#" do
      %svg{viewbox: "0 0 281.19 84.08", xmlns: "http://www.w3.org/2000/svg", height: "31", width: "124"}
        %defs
          :css
            .cls-3{fill:#fff;stroke:#b53d22;stroke-miterlimit:10;}.cls-4{font-size:48px;fill:#fff;font-familyYuGo-Bold-83pv-RKSJ-H, YuGothic;}
        %title アセット 1
        %g{"data-name": "レイヤー 2", id: "レイヤー_2"}
          %g{"data-name": "レイヤー 1", id: "レイヤー_1-2"}
            %polygon.cls-3{points: "36.41 83.5 0.5 62.77 0.5 21.31 36.41 0.58 72.32 21.31 72.32 62.77 36.41 83.5"}
            %polyline.cls-3{points: "0.5 21.31 36.41 42.04 72.32 21.31"}
            %polyline.cls-3{points: "36.41 83.5 36.41 49.36 36.41 42.04"}
            %line.cls-3{x1: "36.41", x2: "0.5", y1: "52.41", y2: "31.67"}
            %line.cls-3{x1: "72.32", x2: "36.41", y1: "33.2", y2: "50.88"}
            %text.cls-4{transform: "translate(86.41 62.77)"} Fmarket

    %span.team-copyright
      .team-copyright__text © Team_66a, Inc.

app/views/layouts/_header.html.haml
%header.header
  .header__contents
    .header__contents__top
      .header__contents__top__title-image
        =link_to root_path do
          = image_tag "/fmarket_logo_red.svg", height:'40', width:'134'
                
      %form.header__contents__top__form{action: "/"}
        %input{name: "keyword", placeholder: "何かお探しですか？", type: "search", value: ""}/
        %button
          %i.fas.fa-search{height: "14", width: "14"}
    .header__contents__row
      =render partial: "layouts/select"
      .l-right
        %ul.login-nav
          - if user_signed_in?
            %li.login_menu
              = link_to root_path, class:"user_icons" do
                %i.far.fa-heart
                %span いいね一覧
            %li.login_menu
              = link_to root_path, class:"user_icons" do
                %i.far.fa-bell
                %span お知らせ
            %li.login_menu
              = link_to root_path, class:"user_icons" do
                %i.fas.fa-check
                %span やることリスト
            %li.login_menu
              = link_to mypage_path, class:"user_icons" do
                %i.fas.fa-user-circle
                %span マイページ

          - else
            %li.login-nav__sign-up
              =link_to "signup" do
                %span 新規会員登録
            %li.login-nav__log-in
              =link_to new_user_session_path do
                %span ログイン

app/views/layouts/_left-menu.html.haml
.main-contents__left-menu
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        マイページ
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        お知らせ
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        やることリスト
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        いいね！一覧
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        出品する
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        出品した商品-出品中
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        出品した商品-取引中
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        出品した商品-売却済み
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        購入した商品-取引中
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        購入した商品-過去の取引
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        ニュース一覧
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        評価一覧
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        ガイド
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        お問い合わせ
      %span.right-arror
        >

  .main-contents__left-menu__menu-title
    メルペイ
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        売上・振込申請
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        ポイント
      %span.right-arror
        >

  .main-contents__left-menu__menu-title
    設定
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        プロフィール
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        発送元・お届け先住所変更
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        支払い方法
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        メール/パスワード
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        本人情報
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side" do
      %span
        電話番号の確認
      %span.right-arror
        >
  .main-contents__left-menu__menu-each
    = link_to "#", class: "side logout" do
      %span
        ログアウト
      %span.right-arror
        >

app/views/layouts/_select.html.haml
%nav.l-left
  %ul.searchs
    %li.searchs__category-search
      = link_to "#" do
        %i.fas.fa-list-ul
        %span カテゴリーから探す
        %ul.category-search__perents
          - @parents.each do |parent|
            %li.category-search__perents__perent
              = link_to "#" do
                =parent.name
              %ul.children
                - parent.children.each do |child|
                  %li.children__child
                    = link_to "#" do
                      =child.name  
                    %ul.grand-children
                      - child.children.each do |grandchild|
                        %li.grand-children__grand-child
                          = link_to "#" do
                            =grandchild.name



    %li.searchs__brand-search
      = link_to "#" do
        %span 
        %i.fas.fa-tag
        %span ブランドから探す
        %ul.brand-search__perents
          - @brands.each do |brand|
            %li.brand-search__perents__perent
              = link_to "#" do
                =brand.name
 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FreemarketSample66a
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://use.fontawesome.com/releases/v5.6.1/css/all.css", rel: "stylesheet"}/

  %body

    = yield

app/views/logouts/index.html.haml
=render partial: "layouts/header"
.nav-bread
  .nav-bread__nav-box
    %ul
      %li<>
        メルカリ
      %li.arrow<>
        >
      %li<>
        = link_to 'マイページ', '＃', class: "editlink"
      %li.arrow<>
        >
      %li.logout<>
        ログアウト


.main-background
  .main-contents
    = render partial: 'layouts/left-menu'
    


    .main-contents__right-box
      .main-contents__right-box__right-inner
        .main-contents__right-box__right-inner__right-logout
          = link_to "#", class: "link-logout" do
            ログアウト


=render partial: "layouts/button"
=render partial: "layouts/banner-bottom"
=render partial: "layouts/footer"